# Generated by Django 5.2.5 on 2025-11-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_id', models.ImageField(unique=True, upload_to='')),
                ('StudentName', models.CharField(max_length=100)),
                ('Total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pnding_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.IntegerField(unique=True)),
                ('StudentName', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Grade', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Subject', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.BigIntegerField(unique=True)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
