# Generated by Django 5.2.5 on 2025-11-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_details',
            name='Fee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
