# Generated by Django 5.2.5 on 2025-11-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_fee_details_fee_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fee_Details',
            new_name='Fee_Details_models',
        ),
        migrations.RenameModel(
            old_name='Student_Details',
            new_name='Student_Details_models',
        ),
        migrations.RenameModel(
            old_name='Teacher_Details',
            new_name='Teacher_Details_models',
        ),
    ]
